spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/funny-deposit?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        url: jdbc:mysql://120.77.83.236:3306/funny_deposit?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
#        password: 123456
        password: 20180907_Deposit
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
# 配置自定义参数
optional:
    params:
        agentId: 10004425
        bussType: 6
        secretKey: "kd7ESeY9izjXggYdCBXjDAR825rTzUvL"
        versionNo: 1.0
    youzan:
      enable: true
      client-id: d42967c0dde9de76ad
      client-secret: c1637f0d0c07d5ec9464411f10a944e8
      kdt-id: 13176063
    fulu:
      enable: true
      no: 804867
      name: lyh512125
      key: 900B44E19971C3BC7EF02E1290CA08D8
      url: http://test.ccapi.soouu.cn/Interface/Method
      notifyUrl: https://www.lckj.shop/api/fulu/order/notify
server:
  http:
    port: 80
  port: 443
  ssl:
    key-store: /app/cert/your-name.jks
    key-store-password: 214997044790232
    key-password: 214997044790232