spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/funny-deposit?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        url: jdbc:mysql://119.23.229.146:3306/funny_deposit_test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
#        password: 123456
        password: miaoChong_20181025
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
# 配置自定义参数
optional:
    params:
        agentId: 48281
        bussType: 6
        secretKey: "01234567890123456789012345678912"
        versionNo: 1.0