spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/funny-deposit?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        url: jdbc:mysql://120.77.83.236:3306/funny_deposit_test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
#        password: 123456
        password: 20180907_Deposit
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
# 配置自定义参数
optional:
    params:
        agentId: 48281
        bussType: 6
        secretKey: "01234567890123456789012345678912"
        versionNo: 1.0
    youzan:
        enable: true
        client-id: f6e4afe3389a0b23d8
        client-secret: c69569f3ce556a212f2d64297ea8d447
        kdt-id: 40430747
    fulu:
        enable: true
        appKey: dmQNHkLro7xRei7ORvviV8acPmrkX9k/t08GJwuTsKWxUP+EQak4jAYszDlF1HcF
        appSecret: 8cf86a60d90d4328a006610e2123612e
        kamiUrl: http://api.open.fulu.com/api/Order/CreateCardOrder
        feiKamiUrl: http://api.open.fulu.com/api/Order/CreateOrder
        fuluCheckUrl: http://api.open.fulu.com/api/Order/GetOrder
        v2Enable: false
        huge: 5
        userId: 803683
        name: lyh512125
        key: CC11F561EBF14204089A5C64DE61C8DF
        url: http://test.ccapi.soouu.cn/Interface/Method
        notifyUrl: https://www.lckj.shop/api/fulu/order/notify
    a:
        enable: true
        appKey: 85AAB222A5CFA60E6B3AB9C272F27078
        checkUrl: https://pdd.paymob.cn/mobileService/xyQuery
        mctNo: 20190608133802330
        url: https://pdd.paymob.cn/mobileService/orderVideo