spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/funny-deposit?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        url: jdbc:mysql://rm-wz91yjst37l4jx2xy.mysql.rds.aliyuncs.com:3306/funny_deposit?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: developer
#        password: 123456
        password: 2019-06-26lckjLCKJ
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
# 配置自定义参数
optional:
    params:
        agentId: 10004425
        bussType: 6
        secretKey: "kd7ESeY9izjXggYdCBXjDAR825rTzUvL"
        versionNo: 1.0
    youzan:
        enable: true
        client-id: d42967c0dde9de76ad
        client-secret: c1637f0d0c07d5ec9464411f10a944e8
        kdt-id: 13176063
    fulu:
        enable: true
        v2Enable: false
        huge: 5
        userId: 804867
        name: lyh512125
        appKey: Q8VLF1U1sBWvx9f6LFVPed18TKzjML+axbFHeW2Aqxi3XzpT+CHNuW4RvHXgetEq
        appSecret: 3fd6e0ab8a9444bdbff1db34d75ec456
        key: 900B44E19971C3BC7EF02E1290CA08D8
        url: http://ccapi.soouu.cn/Interface/Method
        kamiUrl: http://api.open.fulu.com/api/Order/CreateCardOrder
        feiKamiUrl: http://api.open.fulu.com/api/Order/CreateOrder
        fuluCheckUrl: http://api.open.fulu.com/api/Order/GetOrder
        notifyUrl: http://47.107.255.48:81/api/fulu/order/notify
    a:
        enable: true
        appKey: 85AAB222A5CFA60E6B3AB9C272F27078
        clientKey: 32AAB222A5CF4036B3AB9C275427038
        checkUrl: https://pdd.paymob.cn/mobileService/xyQuery
        mctNo: 20190608133802330
        url: https://pdd.paymob.cn/mobileService/orderVideo
    superman:
        enable: true
        username: 13557942290
        password: ab123456
        url: http://chaoren.waa.cn/home/api
#server:
#    http:
#        port: 8081